### ISSUE TITLE
options constructor faild in travis node 6 test

### ISSUE THREAD

**Issue by TA2k** [ioBroker/create-adapter#127]
I created an adapter with the script and get this as a constructor
```
constructor(options) {
		super({
			...options,
			name: "name",
		});
```
In travis with node 8 and 10 this will pass with node 6 I get this:
```
1) Test the adapter (in a mocked environment)
       The adapter starts in normal mode:
     /home/travis/build/xxx/main.js:33
			...options,
			^^^
SyntaxError: Unexpected token ...
      at createScript (vm.js:56:10)
      at Object.runInThisContext (vm.js:97:10)
      at Module.module._compile (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:157:24)
      at Object.replaceJsLoader [as .js] (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:161:9)
      at require (internal/module.js:20:19)
      at loadModuleInternal (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:164:26)
      at Object.loadModuleInHarness (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:183:12)
      at Object.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:79:45)
      at next (native)
      at /home/travis/build/x/node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:9:71
      at __awaiter (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:5:12)
      at Object.startMockAdapter (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:36:12)
      at Context.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:50:114)
      at next (native)
      at /home/travis/build/xxxx/node_modules/@iobroker/testing/build/tests/unit/index.js:9:71
      at __awaiter (node_modules/@iobroker/testing/build/tests/unit/index.js:5:12)
      at Context.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:43:20)
  2) Test the adapter (in a mocked environment)
       The adapter starts in compact mode:
     /home/travis/build/xxxx/main.js:33
			...options,
			^^^
```

**Comment by AlCalzone** [comment]
Since NodeJS 6 is reaching end of life in a month, I think it's fair not to support it in new adapters anymore. If you do want to, change the `super` call to
```js
super(Object.assign({}, options, {
	name: "name",
}));
```

**Comment by AlCalzone** [comment]
Although... when using that syntax, we should probably drop Node6 from the test matrix.

**Comment by TA2k** [comment]
Yes i would agree to drop node6 from travis config file.
Whats about appveyor is there any config file available?

**Comment by AlCalzone** [comment]
Since travis now supports windows, I decided to not include appveyor in the template. It has always been very (too) slow for me.

**Comment by TA2k** [comment]
Maybe you should then remove AppVeyor from the readme template?
