### ISSUE TITLE
tools.js: Yandex translation error if no text provided

### ISSUE THREAD

**Issue by ghost** [ioBroker/create-adapter#462]
Using gulp from command line:
`gulp translateAndUpdateWordsJS --yandex "API Key"`

If there is nothing to translate or the text is blank (""), it throws an error:

> Error: Could not translate to "de": Error: Request failed with status code 400
    at translateYandex (C:\iobroker\node_modules\ioBroker.logparser\lib\tools.js:63:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Same command using google, so `gulp translateAndUpdateWordsJS` works fine.

My workaround: Added `   if(!text) return '';` to tools.js.
```
async function translateText(text, targetLang, yandexApiKey) {
    if (targetLang === 'en') {
        return text;
    }
    if(!text) return '';
    if (yandexApiKey) {
        return await translateYandex(text, targetLang, yandexApiKey);
    } else {
        return await translateGoogle(text, targetLang);
    }
}
```

I would have suggested a pull request, but I was unable to find the tools.js file here.

**Comment by ghost** [comment]
Would be probably even better to not even call the function if there is no text or no translation job to do and provide a log message to the user.
