### ISSUE TITLE
TypeError: _c.includes is not a function

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/create-adapter#590]
It is nowhere noted what version of NodeJS I should use.

Also, the tool allows to run on my NodeJS 10.14.2 (Windows).
But it fails with the following error:
```text
That's it. Please wait a minute while I get this working...
[1/3] Generating files...
TypeError: _c.includes is not a function
    at module.exports.answers (C:\Users\Samuel\AppData\Roaming\npm-cache\_npx\18856\node_modules\@iobroker\create-adapter\build\templates\README.md.js:10:81)
    at Promise.all.templateFiles.map (C:\Users\Samuel\AppData\Roaming\npm-cache\_npx\18856\node_modules\@iobroker\create-adapter\build\src\lib\createAdapter.js:43:32)
    at Array.map (<anonymous>)
    at Object.createFiles (C:\Users\Samuel\AppData\Roaming\npm-cache\_npx\18856\node_modules\@iobroker\create-adapter\build\src\lib\createAdapter.js:37:51)
    at main (C:\Users\Samuel\AppData\Roaming\npm-cache\_npx\18856\node_modules\@iobroker\create-adapter\build\src\cli.js:216:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The tool should either support older NodeJS versions or complain at start-up (or even during npx "installation") that the current NodeJS version is (no longer) supported.

P.S.: The same error was reported this weekend on Discord.

**Comment by AlCalzone** [comment]
There must be something else going on, `Array.includes` is supported since Node 6. The creator is limited to Node 8+:
https://github.com/ioBroker/create-adapter/blob/master/package.json#L27-L29

Do you have a specific answer set that fails or something else I can use to reproduce?

**Comment by AlCalzone** [comment]
Okay, I found it... has nothing to do with Node versions. The `ci` question has a (wrong) default value of `0`, which was left over when switching from multiselect to a normal select.

**Comment by UncleSamSwiss** [comment]
Just installed the latest LTS NodeJS (12.18.4) and got the same error.

**Comment by AlCalzone** [comment]
Yes, `number` has no method `includes` :)

**Comment by UncleSamSwiss** [comment]
Can you please ensure this won't be a problem when replaying a previous create-adapter session with the `--replay` option? Perhaps rename the answer ID?

**Comment by AlCalzone** [comment]
What does the replay functionality do if the replay file contains a non-existing answer ID? Ignore it?

**Comment by AlCalzone** [comment]
In fact, I've changed the check to `===`, so it should not be an error. You're just going to be missing the relevant files if you replay an old session.
