### ISSUE TITLE
build fails for newly created adapter (react admin ui)

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/create-adapter#781]
It seems there is a missing dependency somewhere?

I did not yet change anything on the source files... so I guess this should not happen?

```
D:\iobroker\ioBroker.ico>dev-server watch
Using profile default
Using profile name "default"
Using adapter name "ico"
Install local iobroker.ico
D:\iobroker\ioBroker.ico> npm run build

> iobroker.ico@0.0.1 prebuild D:\iobroker\ioBroker.ico
> rimraf ./build


> iobroker.ico@0.0.1 build D:\iobroker\ioBroker.ico
> npm run build:ts && npm run build:parcel


> iobroker.ico@0.0.1 build:ts D:\iobroker\ioBroker.ico
> tsc -p tsconfig.build.json


> iobroker.ico@0.0.1 build:parcel D:\iobroker\ioBroker.ico
> parcel build admin/src/index.tsx -d admin/build

×  D:\iobroker\ioBroker.ico\node_modules\@iobroker\adapter-react\GenericApp.js:22:44: Cannot resolve dependency '@material-ui/icons/Close'
  20 | var _IconButton = _interopRequireDefault(require("@material-ui/core/IconButton"));
  21 |
> 22 | var _Close = _interopRequireDefault(require("@material-ui/icons/Close"));
     |                                            ^
  23 |
  24 | var _Prompt = _interopRequireDefault(require("./Prompt"));
  25 |
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.ico@0.0.1 build:parcel: `parcel build admin/src/index.tsx -d admin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iobroker.ico@0.0.1 build:parcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\achim\AppData\Roaming\npm-cache\_logs\2021-07-10T06_45_04_211Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.ico@0.0.1 build: `npm run build:ts && npm run build:parcel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iobroker.ico@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\achim\AppData\Roaming\npm-cache\_logs\2021-07-10T06_45_04_234Z-debug.log
index.js watch [profile]

Run ioBroker dev-server and start the adapter in "watch" mode. The adapter will automatically
restart when its source code changes. You may attach a debugger to the running adapter.

Options:
      --version  Show version number                                                       [boolean]
  -t, --temp     Temporary directory where the dev-server data will be located
                                                                   [string] [default: ".dev-server"]
      --help     Show help                                                                 [boolean]
  -n, --noStart  Do not start the adapter itself, only watch for changes and sync them.    [boolean]

Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at DevServer.execSync (C:\Users\achim\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:1106:19)
    at DevServer.installLocalAdapter (C:\Users\achim\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:1060:18)
    at async DevServer.watch (C:\Users\achim\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:275:9)
    at async Object.handler (C:\Users\achim\AppData\Roaming\npm\node_modules\@iobroker\dev-server\dist\index.js:102:28) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 31560,
  stdout: null,
  stderr: null
}

```

//Edit:
I had to add dependency @material-ui/icons to dev-dependencies to get it working.

**Comment by UncleSamSwiss** [comment]
Just add `@material-ui/icons` as a dev dependency for now.
